name: Generate Colorful Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
          
          # Custom color configuration
          color_snake: |
            "#9333EA",    # Main purple
            "#A855F7",    # Light purple
            "#7E22CE"     # Dark purple
          
          color_dots: |
            "#F5F5F5",    # Very light gray background
            "#6B21A8",    # Light contribution
            "#581C87",    # Medium contribution
            "#3B0764",    # More contribution
            "#2E0C51"     # Most contribution

      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
