name: Generate Colorful Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
          
          # Custom color configuration for a rainbow snake
          color_snake: |
            "#FF6B6B",    # Coral red
            "#4ECDC4",    # Turquoise
            "#45B7D1",    # Sky blue
            "#96CEB4"     # Mint green
          
          color_dots: |
            "#FFFFFF",    # White background
            "#D4E4FF",    # Very light contribution
            "#7EB6FF",    # Light contribution
            "#4B83DB",    # Medium contribution
            "#1E56A0"     # Most contribution

      - name: Push Snake SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
